name: FE Build and test

on:
  push:
    branches-ignore:
      - master
    paths:
      - "danet-portal-frontend/**"
  pull_request:
    paths:
      - "danet-portal-frontend/**"
  workflow_dispatch:

jobs:
  build-test-frontend:
    name: Build and test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: danet-portal-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat ../.nvmrc | cut -c 1-2)
        id: nvm
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: npm install && ENVIRONMENT=dev npm run build
      - name: Test
        run: npm test -- --coverage
    # TODO: Build Production
