name: Build and test

on:
  push:
    branches:
      - "!master"
  pull_request:

jobs:
  build-test-frontend:
    name: Build and test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm install && npm run build
      - name: Test
        run: npm test
    # TODO: Deploy to Dev
